AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Moneypenny

Parameters:
  MoneypennyDays:
    Type: String
    Description: Specify comma-delimited list of days you want Moneypenny to save you money. Defaults to every day of the week. (ex. monday,tuesday,wednesday)
    Default: "*" # Defaults to all days of the week
  MoneypennyWeekendMode:
    Type: String
    Description: Specify yes or no whether or not you want Monneypenny to shutdown instances on Friday and wake them up Monday at the specified MonneyAwake time. Defaults to no.
    Default: "no" # Defaults to no, meaning that Moneypenny will defer to the days specified by the user
  MoneypennyAwake:
    Type: String
    Description: Default time to start all of your non-prod instances managed by Moneypenny
    Default: 12:00 # All times are UTC
  MoneypennySleep:
    Type: String
    Description: Default time to stop all of your non-prod instances managed by Moneypenny
    Default: 00:00 # All times are UTC

Resources:
  MoneypennyFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.main
      Runtime: nodejs6.10
      CodeUri: s3://lionshead/moneypenny/dist.zip
      Policies:
       - AWSLambdaExecute # Managed Policy
       - AWSXrayWriteOnlyAccess # Managed Policy
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
               - ec2:DescribeInstances
             Resource: '*'
           - Effect: Allow
             Action:
               - ec2:StartInstance
               - ec2:StopInstance
             Resource: '*'
             Condition:
              StringEquals:
                'tag:Moneypenny': managed
      Environment:
        Variables:
          MoneypennyDays: !Ref MoneypennyDays
          MoneypennyWeekendMode: !Ref MoneypennyWeekendMode
          MoneypennyAwake: !Ref MoneypennyAwake
          MoneypennySleep: !Ref MoneypennySleep
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
